[package]
name = "time_series_start"
version = "0.1.0"
authors = ["Drew Callahan <acallahan@cs.uchicago.edu>"]
edition = "2018"

[dependencies]
num = "0.2"
rocksdb = "0.12.2"
rustfft = "3.0.0"
serde = "1.0.90"
bincode = "1.1.3"
serde_derive = "1.0.90"
rand = "0.6.5"
compression = "0.1.3"